### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by Dandandan**
* Update some dependencies to latest version
* Remove usage of `lexical-core`, use str::parse instead

### CODE REVIEW

**Comment by houqp** [comment]
oh hi @Dandandan :D

**Comment by houqp** [comment]
build failed, so yeah, you probably don't want to touch actix-web because their tokio 1.x support is still beta and going through big refactoring all the time. I have plan to rip it out and switch to warp instead. My experience with actix-web so far has been really unpleasant...

**Comment by Dandandan** [comment]
Hi 😁

Let me see if I can revert that.

Maybe you'll also want to have a look at https://github.com/tokio-rs/axum this seems to getting some traction lately

**Comment by houqp** [comment]
Oh yeah, I was literally trying to find axum because I saw its announcement on reddit the recently but couldn't remember the exact name. Thanks for the pointer!

**Comment by houqp** [comment]
filed https://github.com/roapi/roapi/issues/76.

**Comment by Dandandan** [comment]
@houqp should be fixed now. I minimized the actix / Cargo.lock changes now.

**Review by houqp — APPROVED** [review]

**Comment by Dandandan** [comment]
There was a clippy error

**Pull request merged**
