### PR TITLE
Add dynamic register and update table function.

### PR DESCRIPTION
**Pull request by zemelLeong**
Use example
```
curl -X POST http://172.24.16.1:8080/api/table \
   -H 'Content-Type: application/json' \
   -d '[
    {
        "tableName": "uk_cities2",
        "uri": "./test_data/uk_cities_with_headers.csv"
    }
]'
```

### CODE REVIEW

**Comment by houqp** [comment]
very cool @zemelLeong ! I will take a closer look at this tomorrow :)

**Comment by houqp** [comment]
@zemelLeong I am going to do some more performing testing this weekend. I am little bit concerned about the mutex overhead since it makes the system only able to handle one request at a time. At the very minimum, I think we should at least change it to a reader-writer lock.

**Comment by zemelLeong** [comment]
I will try to modify according your suggestions. but I am a rust noob. may not be able to fix it.

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @zemelLeong for this feature, filed https://github.com/roapi/roapi/issues/155 to as a follow up. I will work on it this weekend if no one gets to it by then.

**Comment by chrisfw** [comment]
@houqp , I just wanted to confirm that this feature only works for file system based tables, correct? 

Thank you,
Chris Whelan

**Comment by houqp** [comment]
@chrisfw it should work for any data source that's supported by roapi, including those hosted in remote storages. But we don't support oracle db as a datasource at the moment, for databases, we only mysql and sqlite.

**Comment by chrisfw** [comment]
@houqp , thank you for following up.  Much appreciated.
Regards,
Chris

**Comment by nicagarc** [comment]
Hi there, does this option support delta tables? I am having trouble calling the API getting 500 response with message "Invalid table URI: unsupported extension in uri". Tried adding "format" field to the payload but it didn't work.

**Comment by houqp** [comment]
@nicagarc can you share the payload you sent here?

**Comment by nicagarc** [comment]
Hi @houqp sure, I used this:

```
[
    {
        "tableName": "project1",
        "uri": "/home/myuser/data/project1/"
    }
]
``` 

Also tried adding a

```
[
    {
        "tableName": "project1",
        "format": "delta",
        "uri": "/home/myuser/data/stage/project1"
    }
]
```

In both cases I get the following response:

```
{
    "code": 500,
    "error": "load_table",
    "message": "Invalid table URI: unsupported extension in uri: /home/myuser/data/stage/project1"
}
```

**Pull request merged**
