### PR TITLE
chore: bump version for axum, dirs, sqlparser, yup-auth2,

### PR DESCRIPTION
**Pull request by tiphaineruy**
#144 

This Start updating versions

### CODE REVIEW

**Comment by houqp** [comment]
Thank you @tiphaineruy for your help on this :)

**Comment by tiphaineruy** [comment]
#144

I've hit a soft wall. I Updated Datafusion and delta to latest.
But one test won't pass and I'm not versed enough yet in datafusion to grasp it.

Before I try to dig in maybe you @houqp could have a look ?
```
failures:

---- query::sql::tests::group_by_aggregation stdout ----
Error: plan_sql: Failed to plan execution from SQL query: Error during planning: Invalid identifier '#landlord' for schema properties.Address, properties.Landlord, properties.Bed, properties.Bath, properties.Occupied, properties.Monthly_Rent, properties.Lease_Expiration_Date
thread 'query::sql::tests::group_by_aggregation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/test/src/lib.rs:195:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by houqp** [comment]
Ha, OK, i think it's because we updated datafusion to make columns case insensitive so the behavior is consistent with postgres. You can just fix the test to lower case the column names.

**Comment by tiphaineruy** [comment]
Indeed It was that.
I "fixed" the test by putting all in lower case.

But that probably  means that there will be new issues at some point. Given that you can register  arrow Fields that are not lowercase.

Which means that indeed the query parser returns a case insensitive query, you can match a "landlord" Field with 
```
SELECT LaNdLoRd from properties
```
But you can't do
```
SELECT landlord from PrOpErTiEs
```
So it seems the table name is not impacted by the  "case insensitive change"

Moreover
If your "Field" is not lowercased
` Field::new("address", DataType::Utf8, false),`

You have now way to match it in the query now.

-----

Anyway I think this PR as done it's course and is good "as is".

**Review by Dandandan — APPROVED** [review]

**Comment by houqp** [comment]
> So it seems the table name is not impacted by the "case insensitive change"

I think this is a bug in datafusion that needs to be fixed because table names are case insensitive in postgres too. Mind filing an upstream ticket?

> when registering the table
>
> You have now way to match it in the query now.

Yeah, I think we might have to force lower case all column names during table registration to avoid confusions :(

**Review by houqp — APPROVED** [review]

**Pull request merged**
